// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/alfathaulia/ca_ecommerce_api/domain"
	mock "github.com/stretchr/testify/mock"
)

// OrderUsecase is an autogenerated mock type for the OrderUsecase type
type OrderUsecase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *OrderUsecase) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, cursor, num
func (_m *OrderUsecase) Fetch(ctx context.Context, cursor string, num int) ([]domain.Order, string, error) {
	ret := _m.Called(ctx, cursor, num)

	var r0 []domain.Order
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []domain.Order); ok {
		r0 = rf(ctx, cursor, num)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, string, int) string); ok {
		r1 = rf(ctx, cursor, num)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, int) error); ok {
		r2 = rf(ctx, cursor, num)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *OrderUsecase) GetByID(ctx context.Context, id int) (domain.Order, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.Order
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, createOrder
func (_m *OrderUsecase) Store(ctx context.Context, createOrder *domain.Order) error {
	ret := _m.Called(ctx, createOrder)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Order) error); ok {
		r0 = rf(ctx, createOrder)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, updateOrder
func (_m *OrderUsecase) Update(ctx context.Context, updateOrder *domain.Order) error {
	ret := _m.Called(ctx, updateOrder)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Order) error); ok {
		r0 = rf(ctx, updateOrder)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
